require_relative "../node_modules/react-native/scripts/react_native_pods"

platform :ios, "15.1"

prepare_react_native_project!

target "sokuriapp" do
  config = use_native_modules!

  use_frameworks! :linkage => :static

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["GCC_PREPROCESSOR_DEFINITIONS"] ||= [
          "$(inherited)",
          "FOLLY_NO_CONFIG=1",
          "FOLLY_MOBILE=1",
          "FOLLY_USE_LIBCPP=1"
        ]
      end
    end
  end
end
