require_relative "../node_modules/react-native/scripts/react_native_pods"

platform :ios, "15.1"

prepare_react_native_project!

target "sokuriapp" do
  config = use_native_modules!

  use_frameworks! :linkage => :static

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :flipper_configuration => FlipperConfiguration.disabled,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    path = "Pods/YogaKit/YogaKit/Source/YGLayout.m"
    if File.exist?(path)
      text = File.read(path)
      fixed = text.gsub(
        "YGNodeSetMeasureFunc(node, YGMeasureView);",
        "YGNodeSetMeasureFunc(node, (YGMeasureFunc) YGMeasureView);"
      )
      File.write(path, fixed)
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "15.1"
        config.build_settings["GCC_PREPROCESSOR_DEFINITIONS"] ||= [
          "$(inherited)",
          "FOLLY_NO_CONFIG=1",
          "FOLLY_MOBILE=1",
          "FOLLY_USE_LIBCPP=1"
        ]
      end
    end
  end
end
